---
- hosts: all
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Disabling Swap on all nodes
    shell: swapoff -a

  - name: Commenting Swap entries in /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(.*swap*)'
     replace: '#\1'

#  - name: Updating OS
#    shell: dnf -y upgrade

  - name: Disable SELinux
    selinux:
     state: disabled

  - name: Kubernetes VxLAN
    shell: modprobe br_netfilter

  - name: Enable IP masquerade
    shell: |
     firewall-cmd --add-masquerade --permanent
     firewall-cmd --reload

  - name: Creating a k8s.conf file
    file:
     path: /etc/sysctl.d/k8s.conf
     state: touch

  - name: Set bridged packets to traverse iptables rules
    blockinfile:
     path: /etc/sysctl.d/k8s.conf
     block: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

  - name: Load new firewall rules
    shell: sysctl --system

