---
- hosts: all
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Add the repository for the docker installation package
    shell: dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install container.io which is not yet provided by the package manager before installing docker
    shell: dnf install https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm

  - name: Then install Docker from the repositories
    shell: dnf install docker-ce --nobest -y

  - name: Starting and enabling the docker service
    service:
     name: docker
     state: started
     enabled: yes

#  - name: Start the docker service
#    shell: systemctl start docker

#  - name: Enable the docker service
#    shell: systemctl enable docker

  - name: Creating a repository file for Kubernetes
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: touch

  - name: Adding repository details in Kubernetes repo file.
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl

  - name: Then update the repo info
    shell: dnf upgrade -y

  - name: Install all the necessary components for Kubernetes
    shell: dnf install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

  - name: Starting and enabling the kubernetes services
    service:
     name: kubelet
     state: started
     enabled: yes

# - name: Installing Docker and firewalld
#    shell: |
#     yum install firewalld -y
#     yum install -y yum-utils device-mapper-persistent-data lvm2
#     yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
#     yum install docker-ce -y --nobest

#  - name: Installing required packages
#    yum:
#     name: "{{ item }}"
#     state: present
#    with_items: "{{ packages }}"

#  - name: Starting and Enabling the required services
#    service:
#     name: "{{ item }}"
#     state: started
#     enabled: yes
#    with_items: "{{ services }}"

